spring:
  application:
    name: Spring Security Demo
  datasource:
    url: jdbc:postgresql://localhost:5431/spring_security
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria

logging:
   level:
     org:
       springframework:
         security: DEBUG
         web:
           filter: TRACE