services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring_security
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
    networks:
      - spring-security-network

networks:
  spring-security-network:

volumes:
  pgdata:
