#Sign up
POST http://localhost:8080/public/register
Content-Type: application/json

{
    "username": "elon",
    "password": "1234567",
    "email": "elon@hotmail.com"
}

###

#Login
POST http://localhost:8080/public/login
Content-Type: application/x-www-form-urlencoded

username=elon&password=1234567


###

#Protected Resource
GET http://localhost:8080/private/user
Content-Type: application/json
